---
# tasks file for opensearch-setup

- name: "Add Opensearch to Yum"
  command: sudo curl -SL https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/opensearch-2.x.repo -o /etc/yum.repos.d/opensearch-2.x.repo

- name: "Install Opensearch"
  yum:
    name: opensearch
    state: latest
    disable_gpg_check: yes

- name: "Configure Opensearch"
  template:
    src: ../templates/opensearch.yml.j2
    dest: /etc/opensearch/opensearch.yml
  notify:
      - Restart Opensearch


